version: "3.1"

services:
    cinema-frontend:
        container_name: cinema-frontend
        image: cinema-frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:80"
