version: "3.1"

services:
    library-backend:
        depends_on:
            - library-postgres
        build:
            context: .
            dockerfile: Dockerfile
        container_name: library-backend
        image: library-backend
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgres:5432/library
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "8080:8080"
    library-postgres:
        image: postgres:alpine
        container_name: library-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=library
        ports:
            - "5000:5432"
